DISCUSSIONS_ENABLED: true
FABRIC:
    ENABLED: true
    APP_KEY: '86ae560a3fc07e7f3b5bca1764973f2345ed73ad'
    BUILD_SECRET: '490cde6571390ecfad8691aaf979050f21efb6e786504543267e74d099e51a08'
FEEDBACK_EMAIL_ADDRESS: 'info@appsembler.com'
SEGMENT_IO:
    ENABLED: true
    SEGMENT_IO_WRITE_KEY: 'HMmiq7YqFWegarBgRH59ktCmKWcBzckW'
